# Generated by Django 4.1 on 2022-08-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='fca',
            new_name='subject_assignment_marks',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='grade_obtained',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='sca',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='tca',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='total_score',
        ),
    ]
