# Generated by Django 4.1 on 2022-08-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0002_rename_fca_studentresult_subject_assignment_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='fca_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='sca_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='term_total',
            field=models.FloatField(default=0),
        ),
    ]
