# Generated by Django 4.1 on 2022-08-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0003_studentresult_fca_score_studentresult_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='grade',
        ),
    ]
