# Generated by Django 4.1 on 2022-08-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0004_remove_studentresult_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='fca_score',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='sca_score',
        ),
    ]
