# Generated by Django 4.1 on 2022-08-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0005_remove_studentresult_fca_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='term_total',
        ),
    ]
