# Generated by Django 4.1 on 2022-08-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0006_remove_studentresult_term_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='buzz',
            field=models.FloatField(default=0),
        ),
    ]
