# Generated by Django 4.1 on 2022-08-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0007_studentresult_buzz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='buzz',
        ),
    ]
