# Generated by Django 4.1 on 2022-08-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0008_remove_studentresult_buzz'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='meatlove',
            field=models.FloatField(default=0),
        ),
    ]
