# Generated by Django 4.1 on 2022-08-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0009_studentresult_meatlove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='meatlove',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='meatpie',
            field=models.TextField(default=''),
        ),
    ]
