# Generated by Django 4.1 on 2022-08-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0010_remove_studentresult_meatlove_studentresult_meatpie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='meatpie',
            field=models.TextField(),
        ),
    ]
