# Generated by Django 4.1 on 2022-08-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0011_alter_studentresult_meatpie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='meatpie',
        ),
    ]
